enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[Sync]
apkmirror-dlurl = "https://apkmirror.com/apk/red-apps-ltd/sync-for-reddit/"
build-mode = "module"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
build-mode = "module"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"

[Strava]
apkmirror-dlurl = "https://apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/"
build-mode = "module"

[Solid Explorer]
apkmirror-dlurl = "https://apkmirror.com/apk/neatbytes/solid-explorer-beta/"
build-mode = "module"

