enable-magisk-update = true

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
build-mode = "module"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
excluded-patches = "'Theme'"

[Solid Explorer]
apkmirror-dlurl = "https://apkmirror.com/apk/neatbytes/solid-explorer-beta/"
