logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
excluded-patches = "'Vanced MicroG support' 'Enable debugging' 'Theme' 'Premium heading'"
included-patches = ""
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Solid Explorer]
apkmirror-dlurl = "https://apkmirror.com/apk/neatbytes/solid-explorer-beta/"
build-mode = "module"
apkmirror-arch = "arm64-v8a"

[Strava]
apkmirror-dlurl = "https://apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/"
build-mode = "module"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
build-mode = "module"

[Sync]
apkmirror-dlurl = "https://apkmirror.com/apk/red-apps-ltd/sync-for-reddit/"
build-mode = "module"
