logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
excluded-patches = "'Vanced MicroG support' 'Enable debugging' 'Theme' 'Premium heading'"

[Solid Explorer]
apkmirror-dlurl = "https://apkmirror.com/apk/neatbytes/solid-explorer-beta/"
build-mode = "module"
apkmirror-arch = "arm64-v8a"

[Strava]
apkmirror-dlurl = "https://apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/"
build-mode = "module"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
build-mode = "module"
